version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - "80:80"
    volumes:
      - nginx_data:/usr/share/nginx/html
    networks:
      - my_network
    environment:
      - NGINX_PORT=80

  alpine:
    image: alpine:latest
    container_name: alpine_container
    ports:
      - "8080:80"
    volumes:
      - alpine_data:/nginx_data
    networks:
      - my_network
    environment:
      - ALPINE_PORT=8080  # ✅ remove spaces around '='

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/nginx_data
    networks:
      - my_network
    environment:
      - REDIS_PORT=6379

volumes:
  nginx_data:
  alpine_data:
  redis_data:

networks:
  my_network:
    driver: bridge
